networks:
  internal:
  edge:


volumes:
  db_data:
  redis_data:
  logs:
  nginx:


x-app-common: &x-app-common
  restart: always
  depends_on:
    db:
      condition: service_healthy
      restart: true
  volumes:
    - ./alembic:/code/alembic
  environment:
    - DOMAIN=${DOMAIN}
    - ENVIRONMENT=${ENVIRONMENT}
    - PROJECT_NAME=${PROJECT_NAME?Variable not set}
    - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
    - SECRET_KEY=${SECRET_KEY?Variable not set}
    - POSTGRES_SERVER=db
    - POSTGRES_PORT=${POSTGRES_PORT}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER?Variable not set}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
    - SENTRY_DSN=${SENTRY_DSN}
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/healthy" ]
    interval: 100s
    timeout: 5s
    retries: 5

services:
  db:
    image: postgres:17
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./db_data:/var/lib/postgresql/data/pgdata
    env_file: .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    networks: [ internal ]

  redirection:
    <<: *x-app-common
    image: 'redirection:${TAG-latest}'
    env_file:
      - redirection/.env
    build:
      context: redirection
      dockerfile: Dockerfile
    networks: [ internal ]

  shortening:
    <<: *x-app-common
    image: 'shortening:${TAG-latest}'
    env_file:
      - .env
    build:
      context: shortening
      dockerfile: Dockerfile
    networks: [ internal ]

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks: [ internal ]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/empty.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - shortening
      - redirection
    networks: [ internal, edge ]

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    networks: [ internal, edge ]
